### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ChopsKingsland** [ifisq/spotify-widget#5]
Can this be done on Windows?

**Comment by GabeHirakawa** [comment]
More than likely not. It requires Xcode to actually load the app onto the phone. It's likely easier to wait until the official Spotify release to come out.

**Comment by ifisq** [comment]
It can't be compiled on Windows because it requires Xcode, and this code isn't functional as WidgetKit on iOS 14 has been heavily updated since this was released. If you'd like to use the Spotify widget, you can find it in my app [here](https://apps.apple.com/app/id1525634753).
